//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

export default class DailySignClient {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  sign(uid: number, gameId: number): void;

  sign(uid: number, gameId: number, callback: (data: void)=>void): void;

  getCurrentMonthSignAwards(uid: number, gameId: number): string;

  getCurrentMonthSignAwards(uid: number, gameId: number, callback: (data: string)=>void): void;
}
