//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Thrift from '../commons/net/thrift'

//HELPER FUNCTIONS AND STRUCTURES

var DailySign_sign_args = function(args) {
  this.uid = null;
  this.gameId = null;
  if (args) {
    if (args.uid !== undefined && args.uid !== null) {
      this.uid = args.uid;
    }
    if (args.gameId !== undefined && args.gameId !== null) {
      this.gameId = args.gameId;
    }
  }
};
DailySign_sign_args.prototype = {};
DailySign_sign_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.uid = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.gameId = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DailySign_sign_args.prototype.write = function(output) {
  output.writeStructBegin('DailySign_sign_args');
  if (this.uid !== null && this.uid !== undefined) {
    output.writeFieldBegin('uid', Thrift.Type.I32, 1);
    output.writeI32(this.uid);
    output.writeFieldEnd();
  }
  if (this.gameId !== null && this.gameId !== undefined) {
    output.writeFieldBegin('gameId', Thrift.Type.I32, 2);
    output.writeI32(this.gameId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DailySign_sign_result = function(args) {
};
DailySign_sign_result.prototype = {};
DailySign_sign_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DailySign_sign_result.prototype.write = function(output) {
  output.writeStructBegin('DailySign_sign_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DailySign_getCurrentMonthSignAwards_args = function(args) {
  this.uid = null;
  this.gameId = null;
  if (args) {
    if (args.uid !== undefined && args.uid !== null) {
      this.uid = args.uid;
    }
    if (args.gameId !== undefined && args.gameId !== null) {
      this.gameId = args.gameId;
    }
  }
};
DailySign_getCurrentMonthSignAwards_args.prototype = {};
DailySign_getCurrentMonthSignAwards_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.uid = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.gameId = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DailySign_getCurrentMonthSignAwards_args.prototype.write = function(output) {
  output.writeStructBegin('DailySign_getCurrentMonthSignAwards_args');
  if (this.uid !== null && this.uid !== undefined) {
    output.writeFieldBegin('uid', Thrift.Type.I32, 1);
    output.writeI32(this.uid);
    output.writeFieldEnd();
  }
  if (this.gameId !== null && this.gameId !== undefined) {
    output.writeFieldBegin('gameId', Thrift.Type.I32, 2);
    output.writeI32(this.gameId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DailySign_getCurrentMonthSignAwards_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
DailySign_getCurrentMonthSignAwards_result.prototype = {};
DailySign_getCurrentMonthSignAwards_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DailySign_getCurrentMonthSignAwards_result.prototype.write = function(output) {
  output.writeStructBegin('DailySign_getCurrentMonthSignAwards_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DailySignClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
DailySignClient.prototype = {};
DailySignClient.prototype.sign = function(uid, gameId, callback) {
  this.send_sign(uid, gameId, callback); 
  if (!callback) {
  this.recv_sign();
  }
};

DailySignClient.prototype.send_sign = function(uid, gameId, callback) {
  this.output.writeMessageBegin('sign', Thrift.MessageType.CALL, this.seqid);
  var params = {
    uid: uid,
    gameId: gameId
  };
  var args = new DailySign_sign_args(params);
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_sign();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

DailySignClient.prototype.recv_sign = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new DailySign_sign_result();
  result.read(this.input);
  this.input.readMessageEnd();

  return;
};
DailySignClient.prototype.getCurrentMonthSignAwards = function(uid, gameId, callback) {
  this.send_getCurrentMonthSignAwards(uid, gameId, callback); 
  if (!callback) {
    return this.recv_getCurrentMonthSignAwards();
  }
};

DailySignClient.prototype.send_getCurrentMonthSignAwards = function(uid, gameId, callback) {
  this.output.writeMessageBegin('getCurrentMonthSignAwards', Thrift.MessageType.CALL, this.seqid);
  var params = {
    uid: uid,
    gameId: gameId
  };
  var args = new DailySign_getCurrentMonthSignAwards_args(params);
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_getCurrentMonthSignAwards();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

DailySignClient.prototype.recv_getCurrentMonthSignAwards = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new DailySign_getCurrentMonthSignAwards_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'getCurrentMonthSignAwards failed: unknown result';
};


module.exports.default = DailySignClient;
