//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


export default class EMapScene {
  id: number;
  mapInfo: string;
  elementTypes: string;
  additionalData: string;
  status: any;

  constructor(args?: { id: number; mapInfo: string; elementTypes: string; additionalData: string; status: any; });
}
