//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

import Thrift from '../commons/net/thrift'
//HELPER FUNCTIONS AND STRUCTURES

var GoodsExchange_exchange_args = function(args) {
  this.uid = null;
  this.gameId = null;
  this.goodsId = null;
  this.addressId = null;
  if (args) {
    if (args.uid !== undefined && args.uid !== null) {
      this.uid = args.uid;
    }
    if (args.gameId !== undefined && args.gameId !== null) {
      this.gameId = args.gameId;
    }
    if (args.goodsId !== undefined && args.goodsId !== null) {
      this.goodsId = args.goodsId;
    }
    if (args.addressId !== undefined && args.addressId !== null) {
      this.addressId = args.addressId;
    }
  }
};
GoodsExchange_exchange_args.prototype = {};
GoodsExchange_exchange_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.uid = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.gameId = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.goodsId = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.I32) {
        this.addressId = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GoodsExchange_exchange_args.prototype.write = function(output) {
  output.writeStructBegin('GoodsExchange_exchange_args');
  if (this.uid !== null && this.uid !== undefined) {
    output.writeFieldBegin('uid', Thrift.Type.I32, 1);
    output.writeI32(this.uid);
    output.writeFieldEnd();
  }
  if (this.gameId !== null && this.gameId !== undefined) {
    output.writeFieldBegin('gameId', Thrift.Type.I32, 2);
    output.writeI32(this.gameId);
    output.writeFieldEnd();
  }
  if (this.goodsId !== null && this.goodsId !== undefined) {
    output.writeFieldBegin('goodsId', Thrift.Type.I32, 3);
    output.writeI32(this.goodsId);
    output.writeFieldEnd();
  }
  if (this.addressId !== null && this.addressId !== undefined) {
    output.writeFieldBegin('addressId', Thrift.Type.I32, 4);
    output.writeI32(this.addressId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var GoodsExchange_exchange_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
GoodsExchange_exchange_result.prototype = {};
GoodsExchange_exchange_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GoodsExchange_exchange_result.prototype.write = function(output) {
  output.writeStructBegin('GoodsExchange_exchange_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var GoodsExchange_getExchangeGoods_args = function(args) {
  this.gameId = null;
  if (args) {
    if (args.gameId !== undefined && args.gameId !== null) {
      this.gameId = args.gameId;
    }
  }
};
GoodsExchange_getExchangeGoods_args.prototype = {};
GoodsExchange_getExchangeGoods_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.gameId = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GoodsExchange_getExchangeGoods_args.prototype.write = function(output) {
  output.writeStructBegin('GoodsExchange_getExchangeGoods_args');
  if (this.gameId !== null && this.gameId !== undefined) {
    output.writeFieldBegin('gameId', Thrift.Type.I32, 1);
    output.writeI32(this.gameId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var GoodsExchange_getExchangeGoods_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
GoodsExchange_getExchangeGoods_result.prototype = {};
GoodsExchange_getExchangeGoods_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

GoodsExchange_getExchangeGoods_result.prototype.write = function(output) {
  output.writeStructBegin('GoodsExchange_getExchangeGoods_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var GoodsExchangeClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
GoodsExchangeClient.prototype = {};
GoodsExchangeClient.prototype.exchange = function(uid, gameId, goodsId, addressId, callback) {
  this.send_exchange(uid, gameId, goodsId, addressId, callback); 
  if (!callback) {
    return this.recv_exchange();
  }
};

GoodsExchangeClient.prototype.send_exchange = function(uid, gameId, goodsId, addressId, callback) {
  this.output.writeMessageBegin('exchange', Thrift.MessageType.CALL, this.seqid);
  var params = {
    uid: uid,
    gameId: gameId,
    goodsId: goodsId,
    addressId: addressId
  };
  var args = new GoodsExchange_exchange_args(params);
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_exchange();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

GoodsExchangeClient.prototype.recv_exchange = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new GoodsExchange_exchange_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'exchange failed: unknown result';
};
GoodsExchangeClient.prototype.getExchangeGoods = function(gameId, callback) {
  this.send_getExchangeGoods(gameId, callback); 
  if (!callback) {
    return this.recv_getExchangeGoods();
  }
};

GoodsExchangeClient.prototype.send_getExchangeGoods = function(gameId, callback) {
  this.output.writeMessageBegin('getExchangeGoods', Thrift.MessageType.CALL, this.seqid);
  var params = {
    gameId: gameId
  };
  var args = new GoodsExchange_getExchangeGoods_args(params);
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_getExchangeGoods();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

GoodsExchangeClient.prototype.recv_getExchangeGoods = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new GoodsExchange_getExchangeGoods_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'getExchangeGoods failed: unknown result';
};


module.exports.default = GoodsExchangeClient;