//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


/**
 * 游戏统计数据服务接口对象
 */
export default class PlayStatisticsClient {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  /**
   * 获取指定玩家当前所有道具
   * 
   * @param uid 需要获取道具信息的玩家ID
   */
  getPlayStatisticsByUid(uid: number): string;

  /**
   * 获取指定玩家当前所有道具
   * 
   * @param uid 需要获取道具信息的玩家ID
   */
  getPlayStatisticsByUid(uid: number, callback: Function): void;
}
