//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


/**
 * 游戏道具服务接口对象
 */
export default class PropClient {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  /**
   * 获取指定玩家当前所有道具
   * 
   * @param uid 需要获取道具信息的玩家ID
   */
  getPlayerProp(uid: number): string;

  /**
   * 获取指定玩家当前所有道具
   * 
   * @param uid 需要获取道具信息的玩家ID
   */
  getPlayerProp(uid: number, callback: (data: string)=>void): void;

  /**
   * 跟新指定玩家当前所有道具
   * 
   * @param uid 需要获取道具信息的玩家ID
   */
  rewardPlayerPropByUnlockZone(uid: number, zoneId: number): string;

  /**
   * 跟新指定玩家当前所有道具
   * 
   * @param uid 需要获取道具信息的玩家ID
   */
  rewardPlayerPropByUnlockZone(uid: number, zoneId: number, callback: (data: string)=>void): void;
}
