//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES
import Thrift from '../commons/net/thrift'

var Ranking_listDailyRanking_args = function(args) {
  this.uid = null;
  this.zoneId = null;
  this.pageNo = null;
  if (args) {
    if (args.uid !== undefined && args.uid !== null) {
      this.uid = args.uid;
    }
    if (args.zoneId !== undefined && args.zoneId !== null) {
      this.zoneId = args.zoneId;
    }
    if (args.pageNo !== undefined && args.pageNo !== null) {
      this.pageNo = args.pageNo;
    }
  }
};
Ranking_listDailyRanking_args.prototype = {};
Ranking_listDailyRanking_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.uid = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.zoneId = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BYTE) {
        this.pageNo = input.readByte().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Ranking_listDailyRanking_args.prototype.write = function(output) {
  output.writeStructBegin('Ranking_listDailyRanking_args');
  if (this.uid !== null && this.uid !== undefined) {
    output.writeFieldBegin('uid', Thrift.Type.I32, 1);
    output.writeI32(this.uid);
    output.writeFieldEnd();
  }
  if (this.zoneId !== null && this.zoneId !== undefined) {
    output.writeFieldBegin('zoneId', Thrift.Type.I32, 2);
    output.writeI32(this.zoneId);
    output.writeFieldEnd();
  }
  if (this.pageNo !== null && this.pageNo !== undefined) {
    output.writeFieldBegin('pageNo', Thrift.Type.BYTE, 3);
    output.writeByte(this.pageNo);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Ranking_listDailyRanking_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
Ranking_listDailyRanking_result.prototype = {};
Ranking_listDailyRanking_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Ranking_listDailyRanking_result.prototype.write = function(output) {
  output.writeStructBegin('Ranking_listDailyRanking_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Ranking_listSpecifiedDailyRanking_args = function(args) {
  this.zoneId = null;
  this.offset = null;
  this.size = null;
  if (args) {
    if (args.zoneId !== undefined && args.zoneId !== null) {
      this.zoneId = args.zoneId;
    }
    if (args.offset !== undefined && args.offset !== null) {
      this.offset = args.offset;
    }
    if (args.size !== undefined && args.size !== null) {
      this.size = args.size;
    }
  }
};
Ranking_listSpecifiedDailyRanking_args.prototype = {};
Ranking_listSpecifiedDailyRanking_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.zoneId = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.offset = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.I32) {
        this.size = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Ranking_listSpecifiedDailyRanking_args.prototype.write = function(output) {
  output.writeStructBegin('Ranking_listSpecifiedDailyRanking_args');
  if (this.zoneId !== null && this.zoneId !== undefined) {
    output.writeFieldBegin('zoneId', Thrift.Type.I32, 1);
    output.writeI32(this.zoneId);
    output.writeFieldEnd();
  }
  if (this.offset !== null && this.offset !== undefined) {
    output.writeFieldBegin('offset', Thrift.Type.I32, 2);
    output.writeI32(this.offset);
    output.writeFieldEnd();
  }
  if (this.size !== null && this.size !== undefined) {
    output.writeFieldBegin('size', Thrift.Type.I32, 3);
    output.writeI32(this.size);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Ranking_listSpecifiedDailyRanking_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
Ranking_listSpecifiedDailyRanking_result.prototype = {};
Ranking_listSpecifiedDailyRanking_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Ranking_listSpecifiedDailyRanking_result.prototype.write = function(output) {
  output.writeStructBegin('Ranking_listSpecifiedDailyRanking_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Ranking_listTotalRanking_args = function(args) {
  this.uid = null;
  this.zoneId = null;
  this.pageNo = null;
  if (args) {
    if (args.uid !== undefined && args.uid !== null) {
      this.uid = args.uid;
    }
    if (args.zoneId !== undefined && args.zoneId !== null) {
      this.zoneId = args.zoneId;
    }
    if (args.pageNo !== undefined && args.pageNo !== null) {
      this.pageNo = args.pageNo;
    }
  }
};
Ranking_listTotalRanking_args.prototype = {};
Ranking_listTotalRanking_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.uid = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.zoneId = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BYTE) {
        this.pageNo = input.readByte().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Ranking_listTotalRanking_args.prototype.write = function(output) {
  output.writeStructBegin('Ranking_listTotalRanking_args');
  if (this.uid !== null && this.uid !== undefined) {
    output.writeFieldBegin('uid', Thrift.Type.I32, 1);
    output.writeI32(this.uid);
    output.writeFieldEnd();
  }
  if (this.zoneId !== null && this.zoneId !== undefined) {
    output.writeFieldBegin('zoneId', Thrift.Type.I32, 2);
    output.writeI32(this.zoneId);
    output.writeFieldEnd();
  }
  if (this.pageNo !== null && this.pageNo !== undefined) {
    output.writeFieldBegin('pageNo', Thrift.Type.BYTE, 3);
    output.writeByte(this.pageNo);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Ranking_listTotalRanking_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
Ranking_listTotalRanking_result.prototype = {};
Ranking_listTotalRanking_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Ranking_listTotalRanking_result.prototype.write = function(output) {
  output.writeStructBegin('Ranking_listTotalRanking_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RankingClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
RankingClient.prototype = {};
RankingClient.prototype.listDailyRanking = function(uid, zoneId, pageNo, callback) {
  this.send_listDailyRanking(uid, zoneId, pageNo, callback); 
  if (!callback) {
    return this.recv_listDailyRanking();
  }
};

RankingClient.prototype.send_listDailyRanking = function(uid, zoneId, pageNo, callback) {
  this.output.writeMessageBegin('listDailyRanking', Thrift.MessageType.CALL, this.seqid);
  var args = new Ranking_listDailyRanking_args();
  args.uid = uid;
  args.zoneId = zoneId;
  args.pageNo = pageNo;
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_listDailyRanking();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

RankingClient.prototype.recv_listDailyRanking = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new Ranking_listDailyRanking_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'listDailyRanking failed: unknown result';
};
RankingClient.prototype.listSpecifiedDailyRanking = function(zoneId, offset, size, callback) {
  this.send_listSpecifiedDailyRanking(zoneId, offset, size, callback); 
  if (!callback) {
    return this.recv_listSpecifiedDailyRanking();
  }
};

RankingClient.prototype.send_listSpecifiedDailyRanking = function(zoneId, offset, size, callback) {
  this.output.writeMessageBegin('listSpecifiedDailyRanking', Thrift.MessageType.CALL, this.seqid);
  var args = new Ranking_listSpecifiedDailyRanking_args();
  args.zoneId = zoneId;
  args.offset = offset;
  args.size = size;
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_listSpecifiedDailyRanking();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

RankingClient.prototype.recv_listSpecifiedDailyRanking = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new Ranking_listSpecifiedDailyRanking_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'listSpecifiedDailyRanking failed: unknown result';
};
RankingClient.prototype.listTotalRanking = function(uid, zoneId, pageNo, callback) {
  this.send_listTotalRanking(uid, zoneId, pageNo, callback); 
  if (!callback) {
    return this.recv_listTotalRanking();
  }
};

RankingClient.prototype.send_listTotalRanking = function(uid, zoneId, pageNo, callback) {
  this.output.writeMessageBegin('listTotalRanking', Thrift.MessageType.CALL, this.seqid);
  var args = new Ranking_listTotalRanking_args();
  args.uid = uid;
  args.zoneId = zoneId;
  args.pageNo = pageNo;
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_listTotalRanking();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

RankingClient.prototype.recv_listTotalRanking = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new Ranking_listTotalRanking_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'listTotalRanking failed: unknown result';
};

module.exports.default = RankingClient;