//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


/**
 * 游戏道具服务接口对象
 */
export default class RewardClient {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  /**
   * 恢复指定玩家体力
   * 
   * @param uid 需要获取道具信息的玩家ID
   */
  recoveryStrength(uid: number): string;

  /**
   * 恢复指定玩家体力
   * 
   * @param uid 需要获取道具信息的玩家ID
   */
  recoveryStrength(uid: number, callback: (data: string)=>void): void;
}
