//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


/**
 * 游戏商店服务接口对象
 */
export default class ShopClient {
  input: Thrift.TJSONProtocol;
  output: Thrift.TJSONProtocol;
  seqid: number;

  constructor(input: Thrift.TJSONProtocol, output?: Thrift.TJSONProtocol);

  /**
   * 根据指定的道具交易类型，获取道具交易套餐项
   * 
   * @param tradingType 道具交易类型
   * @return 道具的交易套餐项
   */
  listPropTradingItems(tradingType: string): string;

  /**
   * 根据指定的道具交易类型，获取道具交易套餐项
   * 
   * @param tradingType 道具交易类型
   * @return 道具的交易套餐项
   */
  listPropTradingItems(tradingType: string, callback: Function): void;

  /**
   * 玩家自己兑换道具
   * 
   * @param uid 玩家ID
   * @param propNum 需要兑换的道具数量
   * @param tradingType 道具交易类型
   */
  exchangeProp(uid: number, propNum: number, tradingType: string): string;

  /**
   * 玩家自己兑换道具
   * 
   * @param uid 玩家ID
   * @param propNum 需要兑换的道具数量
   * @param tradingType 道具交易类型
   */
  exchangeProp(uid: number, propNum: number, tradingType: string, callback: Function): void;
}
