//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES
import Thrift from '../commons/net/thrift'

var Zone_listPKZones_args = function(args) {
};
Zone_listPKZones_args.prototype = {};
Zone_listPKZones_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Zone_listPKZones_args.prototype.write = function(output) {
  output.writeStructBegin('Zone_listPKZones_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Zone_listPKZones_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
Zone_listPKZones_result.prototype = {};
Zone_listPKZones_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Zone_listPKZones_result.prototype.write = function(output) {
  output.writeStructBegin('Zone_listPKZones_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Zone_canAccess_args = function(args) {
  this.zoneId = null;
  this.uid = null;
  if (args) {
    if (args.zoneId !== undefined && args.zoneId !== null) {
      this.zoneId = args.zoneId;
    }
    if (args.uid !== undefined && args.uid !== null) {
      this.uid = args.uid;
    }
  }
};
Zone_canAccess_args.prototype = {};
Zone_canAccess_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.zoneId = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.uid = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Zone_canAccess_args.prototype.write = function(output) {
  output.writeStructBegin('Zone_canAccess_args');
  if (this.zoneId !== null && this.zoneId !== undefined) {
    output.writeFieldBegin('zoneId', Thrift.Type.I32, 1);
    output.writeI32(this.zoneId);
    output.writeFieldEnd();
  }
  if (this.uid !== null && this.uid !== undefined) {
    output.writeFieldBegin('uid', Thrift.Type.I32, 2);
    output.writeI32(this.uid);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var Zone_canAccess_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
Zone_canAccess_result.prototype = {};
Zone_canAccess_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Zone_canAccess_result.prototype.write = function(output) {
  output.writeStructBegin('Zone_canAccess_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ZoneClient = function(input, output) {
    this.input = input;
    this.output = (!output) ? input : output;
    this.seqid = 0;
};
ZoneClient.prototype = {};
ZoneClient.prototype.listPKZones = function(callback) {
  this.send_listPKZones(callback); 
  if (!callback) {
    return this.recv_listPKZones();
  }
};

ZoneClient.prototype.send_listPKZones = function(callback) {
  this.output.writeMessageBegin('listPKZones', Thrift.MessageType.CALL, this.seqid);
  var args = new Zone_listPKZones_args();
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_listPKZones();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

ZoneClient.prototype.recv_listPKZones = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new Zone_listPKZones_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'listPKZones failed: unknown result';
};
ZoneClient.prototype.canAccess = function(zoneId, uid, callback) {
  this.send_canAccess(zoneId, uid, callback); 
  if (!callback) {
    return this.recv_canAccess();
  }
};

ZoneClient.prototype.send_canAccess = function(zoneId, uid, callback) {
  this.output.writeMessageBegin('canAccess', Thrift.MessageType.CALL, this.seqid);
  var args = new Zone_canAccess_args();
  args.zoneId = zoneId;
  args.uid = uid;
  args.write(this.output);
  this.output.writeMessageEnd();
  if (callback) {
    var self = this;
    this.output.getTransport().flush(true, function() {
      var result = null;
      try {
        result = self.recv_canAccess();
      } catch (e) {
        result = e;
      }
      callback(result);
    });
  } else {
    return this.output.getTransport().flush();
  }
};

ZoneClient.prototype.recv_canAccess = function() {
  var ret = this.input.readMessageBegin();
  var fname = ret.fname;
  var mtype = ret.mtype;
  var rseqid = ret.rseqid;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new Zone_canAccess_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'canAccess failed: unknown result';
};

module.exports.default = ZoneClient;